/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import model.DBcon;

/**
 *
 * @author Yasiru
 */
public class accountInfo extends javax.swing.JFrame {
    private String username;
    private String password;
    private String email;
    private String phoneNo;

    /**
     * Creates new form accountInfo
     */
    public accountInfo(String username) {
        initComponents();
        this.username = username;
        retrieveUserData();
        displayUserData();

    }
    
    private void retrieveUserData() {
        try {
            // Connect to the database
            Connection con = DBcon.createConnection();
            PreparedStatement ps = con.prepareStatement("SELECT Password, Email, Phone_no FROM accounts WHERE username = ?");
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                // Retrieve data
                password = rs.getString("password");
                email = rs.getString("email");
                phoneNo = rs.getString("phone_no");
            }
            // Close connections
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void displayUserData() {
        txt_username.setText(username);
        txt_password.setText(password);
        txt_email.setText(email);
        txt_phoneNo.setText(phoneNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_phoneNo = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 287, 217, 37));
        getContentPane().add(txt_phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 436, 217, 37));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 514, 217, 37));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 360, 217, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 363, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Phone No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 439, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 517, -1, -1));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 636, 133, 40));

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 636, 133, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 20, 670, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String newUsername = txt_username.getText();
        String newPassword = String.valueOf(txt_password.getPassword());
        String newPhoneNo = txt_phoneNo.getText();
        String newEmail = txt_email.getText();
        
        StringBuilder errorMessage = new StringBuilder();

        // Validate phone number
        if (newPhoneNo.isEmpty() || newPhoneNo.length() != 10 || !newPhoneNo.startsWith("07") || !newPhoneNo.matches("\\d+")) {
            errorMessage.append("Invalid phone number. Please enter a 10-digit number starting with '07'.\n");
        }

        // Validate email
        if (!newEmail.contains("@") || !newEmail.contains(".com")) {
            errorMessage.append("Invalid email format. Please enter a valid email address.\n");
        }

        // Validate password
        if (!newPassword.matches(".*[A-Z].*") || !newPassword.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")) {
            errorMessage.append("Password must contain at least one uppercase letter and one special character.\n");
        }

        // If any validations fail, display error message
        if (errorMessage.length() > 0) {
            JOptionPane.showMessageDialog(this, errorMessage.toString().trim(), "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // If validations pass, proceed with updating user information

        try {
            Connection con = DBcon.createConnection();
            String query = "UPDATE accounts SET Password=?, Email=?, Phone_no=? WHERE Username=?"; 
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, newPassword);
            pst.setString(2, newEmail);
            pst.setString(3, newPhoneNo);
            pst.setString(4, newUsername);
            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "updated successfully!", "Update Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user information", "Update Error", JOptionPane.ERROR_MESSAGE);
            }

            // Close the database resources
            pst.close();
            con.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose(); // Close the current frame
        new UserDashboard(username).setVisible(true); // Open the UserDashboard frame
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountInfo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phoneNo;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
