package view;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import model.DBcon;



public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_LogRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_adminPortal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 600, 800));
        setMinimumSize(new java.awt.Dimension(600, 800));
        setSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-70, 20, 670, 190);

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_username.setText("Username : ");
        getContentPane().add(lbl_username);
        lbl_username.setBounds(110, 370, 100, 25);

        lbl_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_password.setText("Password :");
        getContentPane().add(lbl_password);
        lbl_password.setBounds(110, 460, 90, 20);
        getContentPane().add(txt_username);
        txt_username.setBounds(240, 370, 210, 30);
        getContentPane().add(txt_password);
        txt_password.setBounds(240, 460, 210, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Not a member yet?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 550, 120, 16);

        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(250, 630, 110, 40);

        btn_LogRegister.setBackground(new java.awt.Color(242, 242, 242));
        btn_LogRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_LogRegister.setForeground(new java.awt.Color(102, 102, 255));
        btn_LogRegister.setText("Register");
        btn_LogRegister.setBorder(null);
        btn_LogRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LogRegister);
        btn_LogRegister.setBounds(340, 550, 80, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("\"For all your bulky shopping needs\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 260, 290, 25);

        btn_adminPortal.setForeground(new java.awt.Color(255, 102, 0));
        btn_adminPortal.setText("Admin Portal");
        btn_adminPortal.setBorder(null);
        btn_adminPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminPortalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_adminPortal);
        btn_adminPortal.setBounds(250, 700, 110, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogRegisterActionPerformed
        dispose(); // Close the current frame
        new register().setVisible(true); // Open the register frame
    }//GEN-LAST:event_btn_LogRegisterActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = txt_username.getText();
        String password = String.valueOf(txt_password.getPassword());
        
        try {
            Connection con = DBcon.createConnection();
            String query = "SELECT * FROM accounts WHERE BINARY Username=? AND BINARY Password=?"; //case sensitive.
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, username);
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                dispose(); // Close 
                new UserDashboard(username).setVisible(true); // Open the userdashboard 
            } else {
                // error message for invalid credentials
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_adminPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminPortalActionPerformed
        dispose();
        new adminLogin().setVisible(true);
    }//GEN-LAST:event_btn_adminPortalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LogRegister;
    private javax.swing.JButton btn_adminPortal;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
