/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.*;
import javax.swing.JOptionPane;
import model.DBcon;

/**
 *
 * @author Yasiru
 */
public class UserDashboard extends javax.swing.JFrame {
    private String username;
    /**
     * Creates new form home
     */
    public UserDashboard(String username) {
        initComponents();
        this.username = username;
        showUsername();
    }
    
    private void showUsername() {
        lbl_showUsername.setText("Welcome, " + username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cart = new javax.swing.JButton();
        btn_editAcc = new javax.swing.JButton();
        btn_groceries = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_showUsername = new javax.swing.JLabel();
        lbl_editAcc = new javax.swing.JLabel();
        lbl_groceries = new javax.swing.JLabel();
        lbl_cart = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/images.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 130));

        btn_cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cart.jpg"))); // NOI18N
        btn_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 140, 130));

        btn_editAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/AccountIcon.png"))); // NOI18N
        btn_editAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editAccActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, 130));

        btn_groceries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/groceries.png"))); // NOI18N
        btn_groceries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_groceriesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_groceries, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 140, 130));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logout.jpg"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 140, 130));

        lbl_showUsername.setText("jLabel2");
        getContentPane().add(lbl_showUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 160, -1));

        lbl_editAcc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_editAcc.setText("Edit Account");
        getContentPane().add(lbl_editAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        lbl_groceries.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_groceries.setText("Groceries");
        getContentPane().add(lbl_groceries, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        lbl_cart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cart.setText("Cart");
        getContentPane().add(lbl_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        lbl_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_logout.setText("Logout");
        getContentPane().add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editAccActionPerformed
       dispose(); // Close the current frame
       new accountInfo(username).setVisible(true); // Open the accountinfo frame
    }//GEN-LAST:event_btn_editAccActionPerformed

    private void btn_groceriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_groceriesActionPerformed
        dispose();//close the form
        new groceries(username).setVisible(true);
    }//GEN-LAST:event_btn_groceriesActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        clearCart(); // Clear the cart
        dispose(); // Close the current frame
        new login().setVisible(true); // Open the login page
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartActionPerformed
        new cart(username).setVisible(true);
    }//GEN-LAST:event_btn_cartActionPerformed
    
    //function to clear cart
    private void clearCart() {
        Connection con = DBcon.createConnection();
        try {
            String query = "DELETE FROM cart";
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error clearing cart: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cart;
    private javax.swing.JButton btn_editAcc;
    private javax.swing.JButton btn_groceries;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cart;
    private javax.swing.JLabel lbl_editAcc;
    private javax.swing.JLabel lbl_groceries;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_showUsername;
    // End of variables declaration//GEN-END:variables
}
